### ISSUE TITLE
heroku support

### ISSUE THREAD

**Issue by rsoorajs** [voldedore/pastebin-telegram-bot#1]
please add heroku support

**Comment by voldedore** [comment]
Hi, you can config your work as the following in order to deploy to heroku.

```
# Procfile
worker: my-telegram-bots
```

```
# heroku.yml
build:
  languages:
    - go

run:
  worker: main
```

```
# main.go
package main

import (
	thebot "github.com/voldedore/pastebin-telegram-bot"
)

func main() {
	go thebot.PasteBinBot()
	select {}
}
```

Then config your private environment variable for the tokens needed, create new worker and start it.

Really sorry for not going in detail due to lack of time.
